### ISSUE TITLE
Too few successful connections

### ISSUE THREAD

**Issue by Ryllaz** [ihorlv/db1000nX100#1]
You can put a lot of ovpn files into `put-your-ovpn-files-here` and connection via some of them is failed.
Worker should try connect until max vpn conections will be established AND until all ovpn files will be processed.  

Now worker is calculating max connections count (based on hardware resources) and go through them. And if some of connections is failed it will remove them from array and will not refill it with new connections from unhandled ovpn files.

**Example**
Config: max connections = 40, total ovpn files count = 250, working ovpn files count = 200, failed ovpn files = 50.

Expected: failed = 15, successful = 25.
Actual: failed = 15, successful = 40.

**Comment by ihorlv** [comment]
Thank you for you intention to make db1000nX100 better.
Please, investigate this issue more precisely. During beginning of the session, when all VPN connections are establishing, failed connections **are refilled** with new connections from unhandled ovpn files. But there is a limit of max failed connections, after which refilling stops and the message is shown: 
**Reached 25 of 40 VPN connections, because 10 connection attempts failed**

The "max fail" limit is calculated as 
$PARALLEL_VPN_CONNECTIONS_QUANTITY / 5
but not less then 10

This limit was designed to prevent too long establishing VPN connections, if for example, one of a user's VPN accounts was banned

**Comment by ihorlv** [comment]
![image](https://user-images.githubusercontent.com/103636784/169716941-89252920-8f3f-48a4-a82d-579f6c502513.png)

**Comment by Ryllaz** [comment]
Well, I think that something is wrong.
I've got this message rcently:
```
Reached 9 of 60 VPN connections, because 21 connection attempts failed
```
I suppose that I should get something like that:
```
Reached 9 of 60 VPN connections, because 51 connection attempts failed
```
or
```
Reached 39 of 60 VPN connections, because 21 connection attempts failed
```
